import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Card } from '../components/ui/Card';
import { Toggle } from '../components/ui/Toggle';
import { PageHeader } from '../components/ui/Shared';
import config from '@eventos/config';
export default function Stats() {
    const [stats, setStats] = useState(config.stats.map(s => ({ ...s })));
    function updateStat(id, field, value) {
        setStats(prev => prev.map(s => s.id === id ? { ...s, [field]: value } : s));
    }
    return (_jsxs("div", { children: [_jsx(PageHeader, { title: "Stats Counters", description: "Edit the statistics displayed on your about page" }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2", children: stats.map(stat => (_jsxs(Card, { children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-lg bg-indigo-50 flex items-center justify-center", children: _jsx("span", { className: "text-lg font-bold text-indigo-600", children: "#" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-gray-900", children: stat.label }), _jsxs("p", { className: "text-xs text-gray-500", children: ["ID: ", stat.id] })] })] }), _jsx(Toggle, { checked: stat.visible, onChange: v => updateStat(stat.id, 'visible', v), size: "sm" })] }), _jsxs("div", { className: "grid grid-cols-3 gap-3", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-[11px] font-medium text-gray-500 mb-1", children: "Value" }), _jsx("input", { type: "number", value: stat.value, onChange: e => updateStat(stat.id, 'value', parseInt(e.target.value) || 0), className: "w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-[11px] font-medium text-gray-500 mb-1", children: "Suffix" }), _jsx("input", { value: stat.suffix, onChange: e => updateStat(stat.id, 'suffix', e.target.value), className: "w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500", placeholder: "+" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-[11px] font-medium text-gray-500 mb-1", children: "Label" }), _jsx("input", { value: stat.label, onChange: e => updateStat(stat.id, 'label', e.target.value), className: "w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" })] })] }), _jsxs("div", { className: "mt-4 p-3 rounded-lg bg-gray-50 text-center", children: [_jsxs("span", { className: "text-3xl font-bold text-indigo-600", children: [stat.value, stat.suffix] }), _jsx("p", { className: "text-xs text-gray-500 mt-1", children: stat.label })] })] }, stat.id))) }), _jsx("div", { className: "mt-6 p-4 rounded-xl bg-blue-50 border border-blue-200", children: _jsxs("p", { className: "text-sm text-blue-800", children: [_jsx("strong", { children: "Note:" }), " Stats defaults come from ", _jsx("code", { className: "bg-blue-100 px-1 rounded", children: "brand.config.ts" }), ". Connect Supabase to persist admin overrides in the ", _jsx("code", { className: "bg-blue-100 px-1 rounded", children: "stats_override" }), " table."] }) })] }));
}
