const config = {
    company: {
        name: 'Vishnu Events & Decor',
        tagline: 'Creating Divine Celebrations',
        description: 'Hyderabad\'s trusted event decorators since 1996. Weddings, haldi, sangeet, engagements, birthdays and home decorations — flowers, draping, lighting and catering handled end to end.',
        founded: 1996,
        email: 'akshaygorenka@gmail.com',
        phone: '+91 80747 50427',
        whatsapp: '+91 80747 50427',
        address: 'Hyderabad, Telangana',
        city: 'Hyderabad',
        mapEmbedUrl: '',
        officeHours: 'Monday – Sunday: 9AM – 8PM',
    },
    brand: {
        colors: {
            primary: '#C9A46A', // Gold
            secondary: '#B68B4C', // Deep Green
            accent: '#8A7B92', // Crimson
            background: '#E9E2F1',
            surface: '#F4EFEA',
            text: '#6B5A4E',
            textMuted: '#9E8E7A',
            border: '#DED5C9',
        },
        fonts: {
            display: 'Playfair Display',
            body: 'Lato',
            accent: 'Great Vibes',
        },
        style: {
            cardRadius: '12px',
            buttonRadius: '6px',
            buttonStyle: 'filled',
            shadowLevel: 'medium',
            animationLevel: 'subtle',
        },
        layout: {
            variant: 'editorial', // Adjusted from festive-editorial unless it is supported
            heroStyle: 'fullscreen',
            navStyle: 'transparent',
        },
    },
    assets: {
        logoLight: '/brand/logo-light.svg',
        logoDark: '/brand/logo-dark.svg',
        favicon: '/brand/favicon.ico',
        ogImage: '/brand/og-image.jpg',
    },
    sections: {
        home: {
            hero: true,
            trustBar: true,
            servicesSnap: true,
            featuredPortfolio: true,
            whyChooseUs: true,
            testimonials: true,
            videoShowreel: true,
            contactCta: true,
            whatsappFloat: true,
        },
        about: {
            story: true,
            missionVision: false,
            team: false,
            stats: true,
            awards: false,
            press: false,
        },
        services: {
            corporate: true,
            weddings: true,
            conferences: false,
            productLaunches: false,
            virtualHybrid: false,
        },
        portfolio: {
            enabled: true,
            categoryFilters: true,
            videoReels: true,
        },
        contact: {
            form: true,
            map: true,
            officeHours: true,
            bookingDeposit: false,
        },
    },
    social: {
        instagram: 'https://www.instagram.com/vishnu.events_',
        facebook: '',
        linkedin: '',
        youtube: '',
        twitter: '',
    },
    content: {
        heroHeadline: 'Creating Divine Celebrations',
        heroSubHeadline: 'Weddings, haldi, sangeet, birthdays & more — trusted by Hyderabad families since 1996',
        heroCta1Label: 'See Our Work',
        heroCta1Href: '/portfolio',
        heroCta2Label: 'Book Your Event',
        heroCta2Href: '/contact',
        aboutStory: 'OG since 1996. Vishnu Events & Decor has been at the heart of Hyderabad\'s celebrations for nearly three decades. From grand wedding mandaps and haldi setups to intimate birthday surprises and home decorations — we bring warmth, colour, and devotion to every occasion we touch.',
        missionStatement: 'To create events that move people — emotionally, aesthetically, and experientially.',
        visionStatement: 'To be the most trusted name in event management across South India.',
        whyUsTitle: 'Why Hyderabad Trusts Us',
        whyUsPoints: [
            {
                icon: 'Sparkles',
                title: 'OG Since 1996',
                body: 'Nearly 30 years of celebrations. We\'ve decorated thousands of homes, mandaps, and halls across Hyderabad.',
            },
            {
                icon: 'Flower2',
                title: 'End-to-End Decor',
                body: 'Flowers, balloons, draping, lighting — we handle every visual element so your venue comes alive.',
            },
            {
                icon: 'Heart',
                title: 'Every Budget, Every Occasion',
                body: 'From a simple birthday surprise to a full wedding setup — we bring the same devotion to every event.',
            },
        ],
        ctaHeadline: 'Let\'s Create Something Beautiful Together',
        ctaBody: 'Tell us about your celebration. We\'ll handle everything from flowers to lights.',
        ctaLabel: 'DM for Bookings',
    },
    stats: [
        { id: 'years', label: 'Years of Experience', value: 29, suffix: '+', visible: true },
        { id: 'events', label: 'Events Executed', value: 1000, suffix: '+', visible: true },
        { id: 'clients', label: 'Happy Families', value: 500, suffix: '+', visible: true },
        { id: 'cities', label: 'City', value: 1, suffix: '', visible: false },
    ],
    services: [
        {
            id: 'weddings',
            title: 'Weddings & Receptions',
            icon: 'Heart',
            shortDesc: 'Grand mandaps, traditional floral arches, and full wedding decor rooted in South Indian tradition.',
            features: ['Mandap design', 'Floral decoration', 'Lighting setup', 'Tent & draping'],
            coverImage: '/content/services/weddings.jpg',
            visible: true,
            comingSoon: false,
        },
        {
            id: 'haldi',
            title: 'Haldi & Sangeet',
            icon: 'Sun',
            shortDesc: 'Vibrant haldi setups and sangeet stage decor that set the tone for the celebrations ahead.',
            features: ['Haldi ceremony decor', 'Sangeet stage setup', 'Floral backdrop', 'Prop styling'],
            coverImage: '/content/services/haldi.jpg',
            visible: true,
            comingSoon: false,
        },
        {
            id: 'engagements',
            title: 'Engagements',
            icon: 'Gem',
            shortDesc: 'Elegant engagement setups with floral backdrops, draping, and stage arrangements.',
            features: ['Stage decoration', 'Floral backdrop', 'Seating arrangement', 'Lighting'],
            coverImage: '/content/services/engagements.jpg',
            visible: true,
            comingSoon: false,
        },
        {
            id: 'birthdays',
            title: 'Birthday Parties',
            icon: 'Cake',
            shortDesc: 'Themed birthday setups for kids and adults — balloons, backdrops, and everything in between.',
            features: ['Theme decoration', 'Balloon arches', 'Photo backdrops', 'Portable surprise setups'],
            coverImage: '/content/services/birthdays.jpg',
            visible: true,
            comingSoon: false,
        },
        {
            id: 'home-decor',
            title: 'Home Decorations',
            icon: 'Home',
            shortDesc: 'Baby showers, bride-to-be setups, housewarming — beautiful decor brought to your doorstep.',
            features: ['Bridal setups', 'Baby shower decor', 'Housewarming florals', 'Festival decoration'],
            coverImage: '/content/services/home-decor.jpg',
            visible: true,
            comingSoon: false,
        },
        {
            id: 'corporate',
            title: 'Corporate Events',
            icon: 'Briefcase',
            shortDesc: 'Stage setups, floral displays, and event decor for organisations, foundations, and corporate occasions.',
            features: ['Stage decoration', 'Floral displays', 'Branding integration', 'Venue dressing'],
            coverImage: '/content/services/corporate.jpg',
            visible: true,
            comingSoon: false,
        },
    ],
    seo: {
        titleTemplate: '%s — Vishnu Events & Decor | Hyderabad',
        defaultTitle: 'Vishnu Events & Decor | Wedding & Event Decorators in Hyderabad',
        description: 'Hyderabad\'s trusted event decorators since 1996. Weddings, haldi, sangeet, engagements, birthdays, home decorations — flowers, lighting, draping & catering.',
        keywords: [
            'event decorators hyderabad',
            'wedding decoration hyderabad',
            'haldi decor hyderabad',
            'sangeet setup hyderabad',
            'birthday decoration hyderabad',
            'home decoration hyderabad',
            'engagement decor hyderabad',
            'vishnu events hyderabad',
        ],
        locale: 'en_IN',
        twitterHandle: '',
    },
    features: {
        razorpay: {
            enabled: false,
            keyId: '',
            depositAmount: 5000,
            depositLabel: 'Booking Deposit',
            refundable: true,
        },
        whatsapp: {
            enabled: true,
            number: '+918074750427',
            defaultMessage: 'Hi! I\'d like to enquire about event decoration. Please share availability and pricing.',
        },
        blog: false,
        analytics: true,
        cookieBanner: false,
        darkModeToggle: false,
    },
};
export default config;
